alallier/reload

README.md
bin/reload
lib/reload-client.js
lib/reload.js

This feature changes the timeout_millis to delay. Now you can enter true in for a delay and reload will wait and check for the server to be up before it reloads.

Changed timeout_millis to delay, allowing reload to wait until the server is up

---

CHANGELOG.md
README.md
bin/reload
lib/reload-client.js
lib/reload-server.js
lib/reload.js

There were two `-d` flags when using the browser development only ability. I renamed delay to reloadDelay

Fixed flags, added a new flag, and updated documentation.

---

README.md
lib/reload-server.js
lib/reload.js

This PR fixes the Node.js option wait flag. Before this PR the wait flag was working properly for the browser development option as it was being checked against a string but not for the Node.js option. I changed the code so that no matter what option you choose to use it checks wait against a bool. I also made some changes to the documentation.

Fixing node.js mode not evaluating wait flag properly

---

lib/reload-client.js
lib/reload.js

In this way, not only nodemon or supervisor can fire a reload event, but you can do:
```javascript
reloadServer = reload(server, app, 1000);
watch.watchTree(__dirname + "/public", function (f, curr, prev) {
console.log("Trying to reload...");
reloadServer.reload();
});
```
**Use case:** let's say that you don't want the server to be restarted each time you change client files. In this way one can let nodemon skipping watching public files and let node server watching and reloading browser each time a change is detected in client files.

Allow reload from node server

---

.gitattributes

Running `reload` results in: `env: node\r: No such file or directory`
Likely due to publishing from a Windows machine with CRLF line endings. Longstanding NPM bug: npm/npm#2097.
This PR adds a `.gitattributes` file to prevent reversion. But note that a new version will need to be published in order to actually fix.

0.8.1 CLI broken on Linux/Mac

---

lib/reload-client.js
package.json

This change will convert `http://` -> `ws://` and `https://` -> `wss://`.

Support WSS when running a HTTPS server

---

lib/reload.js

I was getting random undefined printed on the console. This fix the issue.

Fixed undefined error log on sendMessage

---

README.md
lib/reload-client.js
lib/reload.js

Added the ability to specifying a custom port to run the WebSocket on (Closes #61)

---

.travis.yml

Replace v0.1 and v0.12 with v6 and v7 (stable and dev) (Closes #73)

---

bin/reload
expressSampleApp/package-lock.json
expressSampleApp/package.json
lib/reload.js
package-lock.json
package.json

* Updates dependencies in reload and the sample app to the latest.
* Added `package-lock.json` files for both reload and the sample app.
* Removed death as it was never being used.
* Added supertest script to call server to express sample app to make things [eaiser](https://github.com/jprichardson/reload/issues/89#issuecomment-298204474) to understand.
* Cleaned up some parts of the `package.json` in the sample app

Update dependencies to latest and add `package-lock.json` files 

---

index.js
lib/reload-server.js
lib/reload.js
package.json

Abstracted reload call into an index file, to hide the optional third parameter being used private in the `reload` file. The third argument server is reserved **only** for the command line use.
Related to #102

Kept and abstracted support for server on command line side only

---

CHANGELOG.md
README.md
lib/reload.js

Removed unneeded items from the return API. Just a function called reload is returned which reloads all clients.
The return API is _finally_ documented!
(Closes #120)

Audited and refactored return API (Closes #120)

---

lib/reload-client.js
lib/reload.js

Should fix #126. @yamboy1 had the correct regex to append 80 if the browser didn't supply it, but `reload.js` also needed to be updated to correctly replace the new structure.

Allow for hidden port 80

---

lib/reload-server.js
lib/reload.js
package-lock.json
package.json

* Added mime as a dependency
* Handle all types of files statically
* Inject reload script tag on HTML files only
* Created public/private return API so that `reloadClientCode` (among other things later on need be) could be hidden from the public return API
(Closes #133)

Fixed reload command line regression (Closes #133)

---

bin/reload
lib/reload-server.js

Fix bug when using `dir` flag on command line (Closes #138)

---

README.md
lib/reload.js

Hi,
I put a brief explanation of the problem I was addressing, into README.
There is many solutions of course.
BR
Villem

added: 'wss' to reloadReturn

---

lib/reload-server.js
package-lock.json
package.json

Running `npm audit` shows some vulnerabilities. This fixes those that can be fixed automatically and also replaces the open package with opn to remove dependency on the critical security issue.

Update deps to fix some vulnerability issues

---

bin/reload
lib/reload-server.js

Closes #164 and #166. Introduces an opt-in `-f` or `--fallback` command-line flag, which allows to serve up the start page as a fallback, when the requested route cannot be resolved. This is useful when developing a single-page app that handles routing client-side with HTML5 history API.
Currently, non-resolvable routes such as `/about` or `/blog/some-post` are falling through `serve-static`, which can't match them to a file, and thus returns a `404`. When `-f` flag is on, `reload` will detect these routes, and respond with `index.html` (or custom start page when `-s` is provided). The front-end (e.g. `react` using `react-router-dom`) can then take over the rendering based on the URL path.
As a stretch goal we could also serve up `blog.html` in response to `/blog` if the said file happens …

Add optional --fallback CLI option

---

.npmignore
CONTRIBUTING.md

Add CONTRIBUTING.md

---

README.md
expressSampleApp/server.js

Updated documentation to better reflect the new API with promises (Closes #180)

---

CHANGELOG.md
expressSampleApp/package.json
package-lock.json
package.json

* Updated cli-color from ~1.4.0 to ~2.0.0 - See: https://github.com/alallier/reload/pull/212
* Updated open from ^6.1.0 to ^7.0.0 - See: https://github.com/alallier/reload/pull/213
* Updated mocha from 6.2.1 to 6.2.2 - See: https://github.com/alallier/reload/pull/214
* Updated ws from ~7.1.0 to ~7.2.0 - See: https://github.com/alallier/reload/pull/215

3.0.3 / 2019-10-20

---

lib/reload-server.js

Fixed invalid argument error that cropped up in Node 14 when Reload was writing the temp file on the command line side of Reload. Now Reload writes empty string to the file.
Closes #241

Fix command line Reload in Node 14. Invalid argument error when writing temp file

---

CHANGELOG.md
package-lock.json
package.json

3.1.1 / 2020-09-29
------------------
* Updated mocha from 7.1.2 to 8.1.3 - See: https://github.com/alallier/reload/pull/255
* Updated codecov from 3.7.0 to 3.7.2 - See: https://github.com/alallier/reload/pull/258 and https://github.com/alallier/reload/pull/266
* Updated commander from 5.1.0 to 6.1.0 - See: https://github.com/alallier/reload/pull/259 and https://github.com/alallier/reload/pull/265
* Updated sinon from 9.0.2 to 9.1.0 - See: https://github.com/alallier/reload/pull/264

3.1.1 / 2020-09-29

---

lib/reload-server.js

Fix bug on command line side of reload where reload.js file wasn't being served and index.html auto serving from `/` not having the injected script tag for reload.js file
Fixed bug created by #326

Fix command line bug around reload.js injection

---

bin/reload
package-lock.json
package.json

Swamp out nodemon for supervisor (as supervisor has been end of life for awhile now)
Closes #6

Swap out nodemon for supervisor in reload command line

---

bin/reload

Fix browser command line argument, as it was always launching the browser even when the command line argument was not passed
Closes #384

Reload command line fix browser always opening
